apiVersion: v1
kind: PersistentVolume
metadata:
  name: thai-recipes-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  # Allows multiple pods to read/write
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/Users/lconnell/Development/agentic-rag/data"
    type: DirectoryOrCreate  # Creates the directory if it doesn’t exist
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thai-recipes-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual