name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # Clean up disk space
      - name: Clean up disk space
        run: |
          echo "Disk usage before cleanup:"
          df -h
          # Remove unused Docker data
          docker system prune -af --volumes
          # Clear temporary files
          sudo rm -rf /home/runner/work/_temp/*
          sudo rm -rf /home/runner/.cache/*
          echo "Disk usage after cleanup:"
          df -h

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('src/requirements.txt') }}
          restore-keys: ${{ runner.os }}-buildx-

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/langchain-rag:${{ github.sha }}
            ghcr.io/${{ github.repository }}/langchain-rag:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          # Prune build cache to reduce disk usage
          build-args: |
            --no-cache=false